version: '3'
services:
  backend:
    build: .
    command: >
      sh -c "python main.py"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db